name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.21.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.19.0
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build && pnpm play:build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./.vitepress/dist --project-name=watermark
          packageManager: pnpm
          wranglerVersion: 4
          workingDirectory: playground
